package com.example.booking.repository;

// Importing the Booking entity class
// This is the domain object that represents a booking in the database
// The repository will perform CRUD operations on Booking entities
import com.example.booking.domain.Booking;

// Importing Spring Data JPA repository interface
// JpaRepository provides many built-in methods for database operations
// It uses generics: JpaRepository<EntityType, PrimaryKeyType>
import org.springframework.data.jpa.repository.JpaRepository;

// This is a Repository interface in the Data Access Layer
// Repositories are responsible for data persistence and retrieval
// They act as a bridge between the business logic (services) and the database
// In Spring Data JPA, you just declare interfaces extending JpaRepository
// Spring automatically provides implementations at runtime

// This repository handles all database operations for Booking entities
// It extends JpaRepository<Booking, Long> where:
// - Booking is the entity type we're working with
// - Long is the type of the primary key (id) in the Booking entity
public interface BookingRepository extends JpaRepository<Booking, Long> {

    // This interface is empty because JpaRepository provides all basic CRUD operations:
    // - save(entity) - Insert or update
    // - findById(id) - Find by primary key
    // - findAll() - Get all records
    // - delete(entity) - Delete a record
    // - count() - Count total records
    // - existsById(id) - Check if record exists

    // For custom queries, you would add method declarations here like:
    // List<Booking> findByUserId(Long userId);
    // List<Booking> findByStatus(BookingStatus status);
    // Spring Data JPA would automatically implement these based on method names

    // The actual implementation is generated by Spring at runtime
    // No need to write SQL or implementation code - it's all handled automatically
}
