server:
  port: 8086

spring:
  datasource:
    url: ${INVENTORY_DB_URL:jdbc:h2:mem:inventorydb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${INVENTORY_DB_USERNAME:sa}
    password: ${INVENTORY_DB_PASSWORD:}
    driver-class-name: ${INVENTORY_DB_DRIVER:org.h2.Driver}
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

