server:
  port: 8085

spring:
  datasource:
    url: ${NOTIFICATION_DB_URL:jdbc:h2:mem:notificationdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${NOTIFICATION_DB_USERNAME:sa}
    password: ${NOTIFICATION_DB_PASSWORD:}
    driver-class-name: ${NOTIFICATION_DB_DRIVER:org.h2.Driver}
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

app:
  messaging:
    booking-exchange: booking.exchange
    booking-created-routing-key: booking.created
    booking-created-queue: booking.queue
    payment-exchange: payment.exchange
    payment-routing-key: payment.processed
    payment-queue: payment.queue

