server:
  port: 8084

spring:
  datasource:
    url: ${USER_DB_URL:jdbc:h2:mem:userdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${USER_DB_USERNAME:sa}
    password: ${USER_DB_PASSWORD:}
    driver-class-name: ${USER_DB_DRIVER:org.h2.Driver}
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

